//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsignacionSet
    {
        public AsignacionSet()
        {
            this.Historial_AsignacionesSet = new HashSet<Historial_AsignacionesSet>();
        }
    
        public int Id { get; set; }
        public int ProyectoId { get; set; }
        public int EmpleadoId { get; set; }
        public System.DateTime Fecha_Asignacion { get; set; }
        public Nullable<int> Asignacion_Anterior { get; set; }
        public Nullable<int> InventarioID { get; set; }
    
        public virtual ICollection<Historial_AsignacionesSet> Historial_AsignacionesSet { get; set; }
        public virtual InventarioSet InventarioSet { get; set; }
        public virtual EmpleadoSet EmpleadoSet { get; set; }
        public virtual ProyectoSet ProyectoSet { get; set; }
    }
}
