//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbinventarioEntities : DbContext
    {
        public DbinventarioEntities()
            : base("name=DbinventarioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AlmacenamientoSet> AlmacenamientoSets { get; set; }
        public DbSet<ColorSet> ColorSets { get; set; }
        public DbSet<EmpleadoSet> EmpleadoSets { get; set; }
        public DbSet<Historial_AsignacionesSet> Historial_AsignacionesSet { get; set; }
        public DbSet<MarcaSet> MarcaSets { get; set; }
        public DbSet<ProyectoSet> ProyectoSets { get; set; }
        public DbSet<Tipo_equipoSet> Tipo_equipoSet { get; set; }
        public DbSet<InventarioSet> InventarioSets { get; set; }
        public DbSet<AsignacionSet> AsignacionSets { get; set; }
    }
}
