//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historial_AsignacionesSet
    {
        public int Id { get; set; }
        public int EmpleadoId { get; set; }
        public System.DateTime fecha_asignacion { get; set; }
        public int Asignacion_Id { get; set; }
    
        public virtual EmpleadoSet EmpleadoSet { get; set; }
        public virtual AsignacionSet AsignacionSet { get; set; }
    }
}
