//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventarioSet
    {
        public InventarioSet()
        {
            this.AsignacionSets = new HashSet<AsignacionSet>();
        }
    
        public int Id { get; set; }
        public int MarcaId { get; set; }
        public int ColorId { get; set; }
        public int Tipo_equipoId { get; set; }
        public string Modelo { get; set; }
        public int Cantidad { get; set; }
        public string NumeroSerie { get; set; }
        public string ServicesTag { get; set; }
        public string Procesador { get; set; }
        public string MemoriaRAM { get; set; }
        public string Sistema_Operativo { get; set; }
        public Nullable<int> Almacenamiento { get; set; }
    
        public virtual AlmacenamientoSet AlmacenamientoSet { get; set; }
        public virtual ColorSet ColorSet { get; set; }
        public virtual MarcaSet MarcaSet { get; set; }
        public virtual Tipo_equipoSet Tipo_equipoSet { get; set; }
        public virtual ICollection<AsignacionSet> AsignacionSets { get; set; }
    }
}
