//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_equipoSet
    {
        public Tipo_equipoSet()
        {
            this.InventarioSets = new HashSet<InventarioSet>();
        }
    
        public int Id { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<InventarioSet> InventarioSets { get; set; }
    }
}
